apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: app2
  name: app2
  namespace: default
  annotations:
    service.cloud.tencent.com/pass-to-target: "true"
    service.cloud.tencent.com/specify-protocol: '{"443":{"protocol":["TCP_SSL"],"tls":"app2-cert"}}'
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    k8s-app: app2
  sessionAffinity: None
  type: LoadBalancer
