apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: app
  template:
    metadata:
      labels:
        k8s-app: app
    spec:
      containers:
#        - image: wukongsun/app1:v1.0.0
        - image: registry.rebirthmonkey.com/ops/ops/app1:v1.0.0
          imagePullPolicy: IfNotPresent
          name: app
          ports:
            - containerPort: 8888
              name: insecure
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - mountPath: /etc/app
              name: vol-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - configMap:
            name: vol-config
          name: vol-config
