apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: app
  name: app
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8888
      nodePort: 30888  # 指定节点端口
  selector:
    k8s-app: app
  sessionAffinity: None
  type: NodePort