apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: app
  name: app
spec:
  ports:
    - name: "80"
      port: 80
      protocol: TCP
      targetPort: 8888
  selector:
    k8s-app: app
  sessionAffinity: None
  type: LoadBalancer
